SoftmatDesk/Models/DB_Context/nivel_soporte.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftmatDesk.Models.DB_Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class nivel_soporte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nivel_soporte()
        {
            this.categorias = new HashSet<categorias>();
            this.smusuarios = new HashSet<smusuarios>();
        }
    
        public int Nivel_Soporte_idNivel_Soporte { get; set; }
        public string Nivel_Sop { get; set; }
        public string Descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<categorias> categorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<smusuarios> smusuarios { get; set; }
    }
}

SoftmatDesk/Controllers/nivel_soporteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SoftmatDesk.Models.DB_Context;

namespace SoftmatDesk.Controllers
{
    public class nivel_soporteController : Controller
    {
        private softmatdeskEntities db = new softmatdeskEntities();

        // GET: nivel_soporte
        public async Task<ActionResult> Index()
        {
            return View(await db.nivel_soporte.ToListAsync());
        }

        // GET: nivel_soporte/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            nivel_soporte nivel_soporte = await db.nivel_soporte.FindAsync(id);
            if (nivel_soporte == null)
            {
                return HttpNotFound();
            }
            return View(nivel_soporte);
        }

        // GET: nivel_soporte/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: nivel_soporte/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Nivel_Soporte_idNivel_Soporte,Nivel_Sop,Descripcion")] nivel_soporte nivel_soporte)
        {
            if (ModelState.IsValid)
            {
                db.nivel_soporte.Add(nivel_soporte);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(nivel_soporte);
        }

        // GET: nivel_soporte/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            nivel_soporte nivel_soporte = await db.nivel_soporte.FindAsync(id);
            if (nivel_soporte == null)
            {
                return HttpNotFound();
            }
            return View(nivel_soporte);
        }

        // POST: nivel_soporte/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Nivel_Soporte_idNivel_Soporte,Nivel_Sop,Descripcion")] nivel_soporte nivel_soporte)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nivel_soporte).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(nivel_soporte);
        }
        
        // GET: nivel_soporte/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            nivel_soporte nivel_soporte = await db.nivel_soporte.FindAsync(id);
            if (nivel_soporte == null)
            {
                return HttpNotFound();
            }
            return View(nivel_soporte);
        }

        // POST: nivel_soporte/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            nivel_soporte nivel_soporte = await db.nivel_soporte.FindAsync(id);
            db.nivel_soporte.Remove(nivel_soporte);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SoftmatDesk/Views/nivel_soporte/Create.cshtml
@model SoftmatDesk.Models.DB_Context.nivel_soporte

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Crear cliente</h3>
            </div>
        </div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_content">
                        @using (Html.BeginForm("Create", "nivel_soporte", FormMethod.Post, htmlAttributes: new { @class = "form-horizontal form-label-left" }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="item form-group">

                                @Html.LabelFor(model => model.Nivel_Sop,"Nivel de soporte", htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    @Html.EditorFor(model => model.Nivel_Sop, new { htmlAttributes = new { @class = "form-control col-md-7 col-xs-12", required = "required" } })
                                    @Html.ValidationMessageFor(model => model.Nivel_Sop, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    @Html.TextAreaFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control col-md-7 col-xs-12", required = "required" } })
                                    @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-3">
                                    <input type="submit" value="Agregar" class="btn btn-success" />
                                </div>
                            </div>
                        }
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
}
<!-- /page content -->

@section vendors {
    <!-- iCheck -->
    <script src="~/vendors/iCheck/icheck.min.js"></script>
    <!-- validator -->
    <script src="~/vendors/validator/validator.js"></script>
}

SoftmatDesk/Views/nivel_soporte/Delete.cshtml
@model SoftmatDesk.Models.DB_Context.nivel_soporte

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>nivel_soporte</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nivel_Sop)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nivel_Sop)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SoftmatDesk/Views/nivel_soporte/Details.cshtml
@model SoftmatDesk.Models.DB_Context.nivel_soporte

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Detalles nivel de soporte  </h3>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <div class="clearfix">


                            <div class="x_content">

                                <div class="col-xs-3">
                                    <!-- required for floating -->
                                    <!-- Nav tabs -->
                                    <ul class="nav nav-tabs tabs-left">
                                        <li class="active">
                                            <a href="#home" data-toggle="tab">Descripcion</a>
                                        </li>
                                    </ul>
                                </div>

                                <div class="col-xs-9">
                                    <!-- Tab panes -->
                                    <div class="tab-content">
                                        <div class="tab-pane active" id="home">
                                            <p class="lead">@Html.DisplayFor(model => model.Nivel_Sop)</p>
                                            <p>
                                                @Html.DisplayFor(model => model.Descripcion)
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <p>
                        @Html.ActionLink("Editar", "Edit", new { id = Model.Nivel_Soporte_idNivel_Soporte }, new { @class = "btn btn-info" })
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /page content -->

SoftmatDesk/Views/nivel_soporte/Edit.cshtml
@model SoftmatDesk.Models.DB_Context.nivel_soporte

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>
<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Editar</h3>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_content">

                        @using (Html.BeginForm("Edit", "nivel_soporte", FormMethod.Post, htmlAttributes: new { @class = "form-horizontal form-label-left" }))
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.Nivel_Soporte_idNivel_Soporte)

                                <div class="item form-group">
                                    @Html.LabelFor(model => model.Nivel_Sop, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        @Html.EditorFor(model => model.Nivel_Sop,"Nivel de soporte", new { htmlAttributes = new { @class = "form-control col-md-7 col-xs-12", @readonly="readonly"} })
                                        @Html.ValidationMessageFor(model => model.Nivel_Sop, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="item form-group">
                                    @Html.LabelFor(model => model.Descripcion, "Descrpcion", htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control col-md-7 col-xs-12", required = "required" } })
                                        @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Save" class="btn btn-default" />
                                    </div>
                                </div>
                            </div>
                        }

                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<!-- /page content -->

@section vendors {
    <!-- iCheck -->
    <script src="~/vendors/iCheck/icheck.min.js"></script>
    <!-- validator -->
    <script src="~/vendors/validator/validator.js"></script>
}

SoftmatDesk/Views/nivel_soporte/Index.cshtml
@model IEnumerable<SoftmatDesk.Models.DB_Context.nivel_soporte>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- page content -->
<div class="right_col" role="main">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="dashboard_graph">

                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Listado nivel de soporte</h2>
                            <ul class="nav navbar-right panel_toolbox">
                                <li>
                                    <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                </li>
                                <li>
                                    <a class="close-link"><i class="fa fa-close"></i></a>
                                </li>
                            </ul>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <p class="text-muted font-13 m-b-30">
                                The Buttons extension for DataTables provides a common set of options, API methods and styling to display buttons on a page that will interact with a DataTable. The core library provides the based framework upon which plug-ins can built.
                            </p>
                            <div id="tb_content">
                                @using (Html.BeginForm("Index", "Nivel_soporte", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                                {
                                    <table id="datatable-buttons" class="table table-striped table-bordered">
                                        <thead>
                                            <tr>
                                                <th>
                                                    @Html.DisplayNameFor(model => model.Nivel_Sop)
                                                </th>
                                                <th>
                                                    @Html.DisplayNameFor(model => model.Descripcion)
                                                </th>
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model)
                                            {
                                                <tr>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.Nivel_Sop)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.Descripcion)
                                                    </td>
                                                    <td>
                                                        @Html.ActionLink("Edit", "Edit", new { id = item.Nivel_Soporte_idNivel_Soporte }) |
                                                        @Html.ActionLink("Details", "Details", new { id = item.Nivel_Soporte_idNivel_Soporte }) |
                                                        @Html.ActionLink("Delete", "Delete", new { id = item.Nivel_Soporte_idNivel_Soporte })
                                                    </td>
                                                </tr>
                                            }

                                        </tbody>
                                    </table>
                                }
                            </div>

                        </div>
                    </div>
                </div>

                <div class="clearfix"></div>
            </div>
        </div>

    </div>

</div>

@section vendors {
    <!-- iCheck -->
    <script src="~/vendors/iCheck/icheck.min.js"></script>
    <!-- Datatables -->
    <script src="~/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="~/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="~/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
    <script src="~/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
    <script src="~/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="~/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="~/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="~/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="~/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
    <script src="~/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
    <script src="~/vendors/jszip/dist/jszip.min.js"></script>
    <script src="~/vendors/pdfmake/build/pdfmake.min.js"></script>
    <script src="~/vendors/pdfmake/build/vfs_fonts.js"></script>
}