SoftmatDesk/Models/DB_Context/tickets.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftmatDesk.Models.DB_Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tickets
    {
        public int NoTickets { get; set; }
        public int Categorias_idCategorias { get; set; }
        public int Usuario_idUsuario { get; set; }
        public int Nivel_prioridad_idNivel_prioridad { get; set; }
        public int Cliente_idCliente { get; set; }
        public int Sedes_idSedes { get; set; }
        public string Descripcion_falla { get; set; }
        public System.DateTime Apertura { get; set; }
        public Nullable<System.DateTime> Cierre { get; set; }
        public int SmUsuarios_idsmUsuarios { get; set; }
    
        public virtual categorias categorias { get; set; }
        public virtual cliente cliente { get; set; }
        public virtual nivel_prioridad nivel_prioridad { get; set; }
        public virtual sedes sedes { get; set; }
        public virtual smusuarios smusuarios { get; set; }
        public virtual usuario usuario { get; set; }
    }
}

SoftmatDesk/Controllers/ticketsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SoftmatDesk.Models.DB_Context;

namespace SoftmatDesk.Controllers
{
    public class ticketsController : Controller
    {
        private softmatdeskEntities db = new softmatdeskEntities();

        // GET: tickets
        public async Task<ActionResult> Index()
        {
            var tickets = db.tickets.Include(t => t.categorias).Include(t => t.cliente).Include(t => t.nivel_prioridad).Include(t => t.sedes).Include(t => t.smusuarios).Include(t => t.usuario);
            return View(await tickets.ToListAsync());
        }

        // GET: tickets/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tickets tickets = await db.tickets.FindAsync(id);
            if (tickets == null)
            {
                return HttpNotFound();
            }
            return View(tickets);
        }

        // GET: tickets/Create
        public ActionResult Create()
        {
            ViewBag.Categorias_idCategorias = new SelectList(db.categorias, "idCategorias", "Categoria");
            ViewBag.Cliente_idCliente = new SelectList(db.cliente, "idCliente", "Razon_social");
            ViewBag.Nivel_prioridad_idNivel_prioridad = new SelectList(db.nivel_prioridad, "idNivel_prioridad", "Prioridad");
            ViewBag.Sedes_idSedes = new SelectList(db.sedes, "idSedes", "Nom_Sede");
            ViewBag.SmUsuarios_idsmUsuarios = new SelectList(db.smusuarios, "idsmUsuarios", "Nombres");
            ViewBag.Usuario_idUsuario = new SelectList(db.usuario, "idUsuario", "Nombres");
            return View();
        }

        // POST: tickets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "NoTickets,Categorias_idCategorias,Usuario_idUsuario,Nivel_prioridad_idNivel_prioridad,Cliente_idCliente,Sedes_idSedes,Descripcion_falla,Apertura,Cierre,SmUsuarios_idsmUsuarios")] tickets tickets)
        {
            if (ModelState.IsValid)
            {
                db.tickets.Add(tickets);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.Categorias_idCategorias = new SelectList(db.categorias, "idCategorias", "Categoria", tickets.Categorias_idCategorias);
            ViewBag.Cliente_idCliente = new SelectList(db.cliente, "idCliente", "Razon_social", tickets.Cliente_idCliente);
            ViewBag.Nivel_prioridad_idNivel_prioridad = new SelectList(db.nivel_prioridad, "idNivel_prioridad", "Prioridad", tickets.Nivel_prioridad_idNivel_prioridad);
            ViewBag.Sedes_idSedes = new SelectList(db.sedes, "idSedes", "Nom_Sede", tickets.Sedes_idSedes);
            ViewBag.SmUsuarios_idsmUsuarios = new SelectList(db.smusuarios, "idsmUsuarios", "Nombres", tickets.SmUsuarios_idsmUsuarios);
            ViewBag.Usuario_idUsuario = new SelectList(db.usuario, "idUsuario", "Nombres", tickets.Usuario_idUsuario);
            return View(tickets);
        }

        // GET: tickets/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tickets tickets = await db.tickets.FindAsync(id);
            if (tickets == null)
            {
                return HttpNotFound();
            }
            ViewBag.Categorias_idCategorias = new SelectList(db.categorias, "idCategorias", "Categoria", tickets.Categorias_idCategorias);
            ViewBag.Cliente_idCliente = new SelectList(db.cliente, "idCliente", "Razon_social", tickets.Cliente_idCliente);
            ViewBag.Nivel_prioridad_idNivel_prioridad = new SelectList(db.nivel_prioridad, "idNivel_prioridad", "Prioridad", tickets.Nivel_prioridad_idNivel_prioridad);
            ViewBag.Sedes_idSedes = new SelectList(db.sedes, "idSedes", "Nom_Sede", tickets.Sedes_idSedes);
            ViewBag.SmUsuarios_idsmUsuarios = new SelectList(db.smusuarios, "idsmUsuarios", "Nombres", tickets.SmUsuarios_idsmUsuarios);
            ViewBag.Usuario_idUsuario = new SelectList(db.usuario, "idUsuario", "Nombres", tickets.Usuario_idUsuario);
            return View(tickets);
        }

        // POST: tickets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "NoTickets,Categorias_idCategorias,Usuario_idUsuario,Nivel_prioridad_idNivel_prioridad,Cliente_idCliente,Sedes_idSedes,Descripcion_falla,Apertura,Cierre,SmUsuarios_idsmUsuarios")] tickets tickets)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tickets).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.Categorias_idCategorias = new SelectList(db.categorias, "idCategorias", "Categoria", tickets.Categorias_idCategorias);
            ViewBag.Cliente_idCliente = new SelectList(db.cliente, "idCliente", "Razon_social", tickets.Cliente_idCliente);
            ViewBag.Nivel_prioridad_idNivel_prioridad = new SelectList(db.nivel_prioridad, "idNivel_prioridad", "Prioridad", tickets.Nivel_prioridad_idNivel_prioridad);
            ViewBag.Sedes_idSedes = new SelectList(db.sedes, "idSedes", "Nom_Sede", tickets.Sedes_idSedes);
            ViewBag.SmUsuarios_idsmUsuarios = new SelectList(db.smusuarios, "idsmUsuarios", "Nombres", tickets.SmUsuarios_idsmUsuarios);
            ViewBag.Usuario_idUsuario = new SelectList(db.usuario, "idUsuario", "Nombres", tickets.Usuario_idUsuario);
            return View(tickets);
        }

        // GET: tickets/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tickets tickets = await db.tickets.FindAsync(id);
            if (tickets == null)
            {
                return HttpNotFound();
            }
            return View(tickets);
        }

        // POST: tickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            tickets tickets = await db.tickets.FindAsync(id);
            db.tickets.Remove(tickets);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SoftmatDesk/Views/tickets/Create.cshtml
@model SoftmatDesk.Models.DB_Context.tickets

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tickets</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Categorias_idCategorias, "Categorias_idCategorias", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Categorias_idCategorias", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Categorias_idCategorias, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Usuario_idUsuario, "Usuario_idUsuario", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Usuario_idUsuario", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Usuario_idUsuario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nivel_prioridad_idNivel_prioridad, "Nivel_prioridad_idNivel_prioridad", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Nivel_prioridad_idNivel_prioridad", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Nivel_prioridad_idNivel_prioridad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cliente_idCliente, "Cliente_idCliente", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Cliente_idCliente", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Cliente_idCliente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sedes_idSedes, "Sedes_idSedes", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Sedes_idSedes", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Sedes_idSedes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion_falla, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion_falla, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion_falla, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apertura, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apertura, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apertura, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cierre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cierre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cierre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SmUsuarios_idsmUsuarios, "SmUsuarios_idsmUsuarios", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SmUsuarios_idsmUsuarios", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SmUsuarios_idsmUsuarios, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SoftmatDesk/Views/tickets/Delete.cshtml
@model SoftmatDesk.Models.DB_Context.tickets

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tickets</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Descripcion_falla)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion_falla)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apertura)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apertura)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cierre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cierre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.categorias.Categoria)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categorias.Categoria)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cliente.Razon_social)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cliente.Razon_social)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nivel_prioridad.Prioridad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nivel_prioridad.Prioridad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sedes.Nom_Sede)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sedes.Nom_Sede)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.smusuarios.Nombres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.smusuarios.Nombres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.usuario.Nombres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.usuario.Nombres)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SoftmatDesk/Views/tickets/Details.cshtml
@model SoftmatDesk.Models.DB_Context.tickets

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>tickets</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Descripcion_falla)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion_falla)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apertura)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apertura)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cierre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cierre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.categorias.Categoria)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categorias.Categoria)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cliente.Razon_social)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cliente.Razon_social)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nivel_prioridad.Prioridad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nivel_prioridad.Prioridad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sedes.Nom_Sede)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sedes.Nom_Sede)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.smusuarios.Nombres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.smusuarios.Nombres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.usuario.Nombres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.usuario.Nombres)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.NoTickets }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SoftmatDesk/Views/tickets/Edit.cshtml
@model SoftmatDesk.Models.DB_Context.tickets

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tickets</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.NoTickets)

        <div class="form-group">
            @Html.LabelFor(model => model.Categorias_idCategorias, "Categorias_idCategorias", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Categorias_idCategorias", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Categorias_idCategorias, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Usuario_idUsuario, "Usuario_idUsuario", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Usuario_idUsuario", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Usuario_idUsuario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nivel_prioridad_idNivel_prioridad, "Nivel_prioridad_idNivel_prioridad", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Nivel_prioridad_idNivel_prioridad", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Nivel_prioridad_idNivel_prioridad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cliente_idCliente, "Cliente_idCliente", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Cliente_idCliente", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Cliente_idCliente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sedes_idSedes, "Sedes_idSedes", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Sedes_idSedes", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Sedes_idSedes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion_falla, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion_falla, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion_falla, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apertura, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apertura, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apertura, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cierre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cierre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cierre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SmUsuarios_idsmUsuarios, "SmUsuarios_idsmUsuarios", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SmUsuarios_idsmUsuarios", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SmUsuarios_idsmUsuarios, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SoftmatDesk/Views/tickets/Index.cshtml
@model IEnumerable<SoftmatDesk.Models.DB_Context.tickets>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!-- page content -->
<div class="right_col" role="main">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="dashboard_graph">

                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Listado de Tickets</h2>
                            <ul class="nav navbar-right panel_toolbox">
                                <li>
                                    <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                </li>
                                <li>
                                    <a class="close-link"><i class="fa fa-close"></i></a>
                                </li>
                            </ul>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <p class="text-muted font-13 m-b-30">
                                The Buttons extension for DataTables provides a common set of options, API methods and styling to display buttons on a page that will interact with a DataTable. The core library provides the based framework upon which plug-ins can built.
                            </p>
                            <div id="tb_content">
                                @using (Html.BeginForm("Index", "tickets", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                                {
                                    <table id="datatable-buttons" class="table table-striped table-bordered">
                                        <thead>
                                            <tr>
                                                <th>
                                                    @Html.DisplayNameFor(model => model.Descripcion_falla)
                                                </th>
                                                <th>
                                                    @Html.DisplayNameFor(model => model.Apertura)
                                                </th>
                                                <th>
                                                    @Html.DisplayNameFor(model => model.Cierre)
                                                </th>
                                                <th>
                                                    @Html.DisplayNameFor(model => model.categorias.Categoria)
                                                </th>
                                                <th>
                                                    @Html.DisplayNameFor(model => model.cliente.Razon_social)
                                                </th>
                                                <th>
                                                    @Html.DisplayNameFor(model => model.nivel_prioridad.Prioridad)
                                                </th>
                                                <th>
                                                    @Html.DisplayNameFor(model => model.sedes.Nom_Sede)
                                                </th>
                                                <th>
                                                    @Html.DisplayNameFor(model => model.smusuarios.Nombres)
                                                </th>
                                                <th>
                                                    @Html.DisplayNameFor(model => model.usuario.Nombres)
                                                </th>
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model)
                                            {
                                                <tr>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.Descripcion_falla)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.Apertura)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.Cierre)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.categorias.Categoria)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.cliente.Razon_social)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.nivel_prioridad.Prioridad)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.sedes.Nom_Sede)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.smusuarios.Nombres)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.usuario.Nombres)
                                                    </td>
                                                    <td>
                                                        @Html.ActionLink("Edit", "Edit", new { id = item.NoTickets }) |
                                                        @Html.ActionLink("Details", "Details", new { id = item.NoTickets }) |
                                                        @Html.ActionLink("Delete", "Delete", new { id = item.NoTickets })
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                }
                            </div>

                        </div>
                    </div>
                </div>

                <div class="clearfix"></div>
            </div>
        </div>

    </div>

</div>

@section vendors {
    <!-- iCheck -->
    <script src="~/vendors/iCheck/icheck.min.js"></script>
    <!-- Datatables -->
    <script src="~/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="~/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="~/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
    <script src="~/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
    <script src="~/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="~/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="~/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="~/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="~/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
    <script src="~/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
    <script src="~/vendors/jszip/dist/jszip.min.js"></script>
    <script src="~/vendors/pdfmake/build/pdfmake.min.js"></script>
    <script src="~/vendors/pdfmake/build/vfs_fonts.js"></script>
}