SoftmatDesk/Models/DB_Context/nivel_prioridad.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftmatDesk.Models.DB_Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class nivel_prioridad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nivel_prioridad()
        {
            this.tickets = new HashSet<tickets>();
        }
    
        public int idNivel_prioridad { get; set; }
        public string Prioridad { get; set; }
        public Nullable<System.TimeSpan> Tiempo_ejecucion { get; set; }
        public string Descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tickets> tickets { get; set; }
    }
}

SoftmatDesk/Controllers/nivel_prioridadController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SoftmatDesk.Models.DB_Context;

namespace SoftmatDesk.Controllers
{
    public class nivel_prioridadController : Controller
    {
        private softmatdeskEntities db = new softmatdeskEntities();

        // GET: nivel_prioridad
        public async Task<ActionResult> Index()
        {
            return View(await db.nivel_prioridad.ToListAsync());
        }

        // GET: nivel_prioridad/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            nivel_prioridad nivel_prioridad = await db.nivel_prioridad.FindAsync(id);
            if (nivel_prioridad == null)
            {
                return HttpNotFound();
            }
            return View(nivel_prioridad);
        }

        // GET: nivel_prioridad/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: nivel_prioridad/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "idNivel_prioridad,Prioridad,Tiempo_ejecucion,Descripcion")] nivel_prioridad nivel_prioridad)
        {
            if (ModelState.IsValid)
            {
                db.nivel_prioridad.Add(nivel_prioridad);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(nivel_prioridad);
        }

        // GET: nivel_prioridad/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            nivel_prioridad nivel_prioridad = await db.nivel_prioridad.FindAsync(id);
            if (nivel_prioridad == null)
            {
                return HttpNotFound();
            }
            return View(nivel_prioridad);
        }

        // POST: nivel_prioridad/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "idNivel_prioridad,Prioridad,Tiempo_ejecucion,Descripcion")] nivel_prioridad nivel_prioridad)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nivel_prioridad).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(nivel_prioridad);
        }

        // GET: nivel_prioridad/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            nivel_prioridad nivel_prioridad = await db.nivel_prioridad.FindAsync(id);
            if (nivel_prioridad == null)
            {
                return HttpNotFound();
            }
            return View(nivel_prioridad);
        }

        // POST: nivel_prioridad/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            nivel_prioridad nivel_prioridad = await db.nivel_prioridad.FindAsync(id);
            db.nivel_prioridad.Remove(nivel_prioridad);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SoftmatDesk/Views/nivel_prioridad/Create.cshtml
@model SoftmatDesk.Models.DB_Context.nivel_prioridad

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Crear nivel de prioridad</h3>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_content">
                        @using (Html.BeginForm("Create", "nivel_prioridad", FormMethod.Post, htmlAttributes: new { @class = "form-horizontal form-label-left" }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="item form-group">
                                @Html.LabelFor(model => model.Prioridad, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    @Html.EditorFor(model => model.Prioridad, new { htmlAttributes = new { @class = "form-control col-md-7 col-xs-12", required = "required" } })
                                    @Html.ValidationMessageFor(model => model.Prioridad, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Tiempo_ejecucion,"Tiempo de ejecución", htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    @Html.EditorFor(model => model.Tiempo_ejecucion, new { htmlAttributes = new { @class = "form-control col-md-7 col-xs-12", placeholder = "HH:MM:SS", required = "required" } })
                                    @Html.ValidationMessageFor(model => model.Tiempo_ejecucion, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    @Html.TextAreaFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control col-md-7 col-xs-12", required = "required" } })
                                    @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-3">
                                    <input type="submit" value="Agregar" class="btn btn-success" />
                                </div>
                            </div>
                        }
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<!-- /page content -->

@section vendors {
    <!-- iCheck -->
    <script src="~/vendors/iCheck/icheck.min.js"></script>
    <!-- validator -->
    <script src="~/vendors/validator/validator.js"></script>
}

SoftmatDesk/Views/nivel_prioridad/Delete.cshtml
@model SoftmatDesk.Models.DB_Context.nivel_prioridad

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>nivel_prioridad</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Prioridad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prioridad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tiempo_ejecucion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tiempo_ejecucion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SoftmatDesk/Views/nivel_prioridad/Details.cshtml
@model SoftmatDesk.Models.DB_Context.nivel_prioridad

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Detalles nivel de prioridad  </h3>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <div class="clearfix">


                            <div class="x_content">

                                <div class="col-xs-3">
                                    <!-- required for floating -->
                                    <!-- Nav tabs -->
                                    <ul class="nav nav-tabs tabs-left">
                                        <li class="active">
                                            <a href="#home" data-toggle="tab">Descripcion</a>
                                        </li>
                                    </ul>
                                </div>

                                <div class="col-xs-9">
                                    <!-- Tab panes -->
                                    <div class="tab-content">
                                        <div class="tab-pane active" id="home">
                                            <p class="lead">@Html.DisplayFor(model => model.Prioridad)</p>
                                            <p>
                                                @Html.DisplayFor(model => model.Descripcion) en un tiempo de ejecucion de @Html.DisplayFor(model => model.Tiempo_ejecucion) (HH:MM:SS)
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <p>
                        @Html.ActionLink("Editar", "Edit", new { id = Model.idNivel_prioridad }, new { @class = "btn btn-info" })
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /page content -->

SoftmatDesk/Views/nivel_prioridad/Edit.cshtml
@model SoftmatDesk.Models.DB_Context.nivel_prioridad

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Crear nivel de prioridad</h3>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_content">
                        @using (Html.BeginForm("Edit", "nivel_prioridad", FormMethod.Post, htmlAttributes: new { @class = "form-horizontal form-label-left" }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            @Html.HiddenFor(model => model.idNivel_prioridad)

                            <div class="item form-group">
                                @Html.LabelFor(model => model.Prioridad, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    @Html.EditorFor(model => model.Prioridad, new { htmlAttributes = new { @class = "form-control col-md-7 col-xs-12", @readonly = "readonly" } })
                                    @Html.ValidationMessageFor(model => model.Prioridad, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Tiempo_ejecucion, "Tiempo de ejecución", htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    @Html.EditorFor(model => model.Tiempo_ejecucion, new { htmlAttributes = new { @class = "form-control col-md-7 col-xs-12", placeholder = "HH:MM:SS", required = "required" } })
                                    @Html.ValidationMessageFor(model => model.Tiempo_ejecucion, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    @Html.TextAreaFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control col-md-7 col-xs-12", required = "required" } })
                                    @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-3">
                                    <input type="submit" value="Guardar" class="btn btn-success" />
                                </div>
                            </div>
                        }
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<!-- /page content -->

@section vendors {
    <!-- iCheck -->
    <script src="~/vendors/iCheck/icheck.min.js"></script>
    <!-- validator -->
    <script src="~/vendors/validator/validator.js"></script>
}

SoftmatDesk/Views/nivel_prioridad/Index.cshtml
@model IEnumerable<SoftmatDesk.Models.DB_Context.nivel_prioridad>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- page content -->
<div class="right_col" role="main">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="dashboard_graph">

                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Listado nivel prioridad</h2>
                            <ul class="nav navbar-right panel_toolbox">
                                <li>
                                    <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                </li>
                                <li>
                                    <a class="close-link"><i class="fa fa-close"></i></a>
                                </li>
                            </ul>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <p class="text-muted font-13 m-b-30">
                                The Buttons extension for DataTables provides a common set of options, API methods and styling to display buttons on a page that will interact with a DataTable. The core library provides the based framework upon which plug-ins can built.
                            </p>
                            <div id="tb_content">
                                @using (Html.BeginForm("Index", "Nivel_prioridad", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                                {
                                    <table id="datatable-buttons" class="table table-striped table-bordered">
                                        <thead>
                                            <tr>
                                                <th>
                                                    @Html.DisplayNameFor(model => model.Prioridad)
                                                </th>
                                                <th>
                                                    @Html.DisplayNameFor(model => model.Tiempo_ejecucion)
                                                </th>
                                                <th>
                                                    @Html.DisplayNameFor(model => model.Descripcion)
                                                </th>
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model)
                                            {
                                                <tr>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.Prioridad)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.Tiempo_ejecucion)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.Descripcion)
                                                    </td>
                                                    <td>
                                                        @Html.ActionLink("Edit", "Edit", new { id = item.idNivel_prioridad }) |
                                                        @Html.ActionLink("Details", "Details", new { id = item.idNivel_prioridad }) |
                                                        @Html.ActionLink("Delete", "Delete", new { id = item.idNivel_prioridad })
                                                    </td>
                                                </tr>
                                            }

                                        </tbody>
                                    </table>
                                }
                            </div>

                        </div>
                    </div>
                </div>

                <div class="clearfix"></div>
            </div>
        </div>

    </div>

</div>

@section vendors {
    <!-- iCheck -->
    <script src="~/vendors/iCheck/icheck.min.js"></script>
    <!-- Datatables -->
    <script src="~/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="~/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="~/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
    <script src="~/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
    <script src="~/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="~/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="~/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="~/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="~/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
    <script src="~/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
    <script src="~/vendors/jszip/dist/jszip.min.js"></script>
    <script src="~/vendors/pdfmake/build/pdfmake.min.js"></script>
    <script src="~/vendors/pdfmake/build/vfs_fonts.js"></script>
}